# $Id: META.yml 303 2005-03-05 02:53:11Z claco $
name:         AxKit-XSP-Currency
version:      0.03
version_from: lib\AxKit\XSP\Currency.pm
installdirs:  site
license:      perl
requires:
    AxKit:
	Locale::Currency::Format:
distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
